version: "3.9"
services:
  postgres:
    image: postgres:13.3
    container_name: postgres_siz2
    environment:
      POSTGRES_DB: "siz_db"
      POSTGRES_USER: "chugun"
      POSTGRES_PASSWORD: "123456"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    restart: always
    networks:
      node_net:
        ipv4_address: 172.28.1.3

  pgadmin:
    user: root
    container_name: pgadmin_container2
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "t.chugunova24@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ${DATA_PATH_HOST}/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      node_net:
        ipv4_address: 172.28.1.4

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16